pipeline {
    agent none  // This means no global agent

    stages {
        stage('Build Maven') {
            agent {
                docker { image 'maven:3.8.1-adoptopenjdk-11' }
            }
            steps {
                sh 'mvn clean install'
            }
        }

        stage('Build Node') {
            agent {
                docker { image 'node:16-alpine' }
            }
            steps {
                sh 'npm install'
            }
        }
    }
}
